name: Django Project Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and run containers
        run: docker-compose up --build -d

      - name: Wait for backend to be ready
        run: sleep 10

      - name: Install test dependencies (flake8, pytest)
        run: docker exec backend pip install flake8 pytest

      - name: Run Tests
        run: docker exec backend sh -c "flake8 . && pytest ."
