name: Django Project Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        uses: docker/compose-action@v3
        with:
          compose-file: docker-compose.yml
          up: true
          build: true
          detach: true

      - name: Wait for backend to be ready
        run: sleep 10

      - name: Install flake8 and pytest in backend container
        run: docker exec backend pip install flake8 pytest

      - name: Run flake8 and pytest
        run: docker exec backend sh -c "flake8 . && pytest ."
